# Generated by Django 5.0.4 on 2026-02-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anquantianshu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anquanbiaoti', models.TextField(verbose_name='安全标题')),
                ('user', models.TextField(blank=True, null=True, verbose_name='发布人')),
                ('anquanneirong', models.TextField(blank=True, null=True, verbose_name='安全内容')),
                ('anquanfenlei', models.CharField(choices=[('劳动安全', '劳动安全'), ('行车安全', '行车安全'), ('车辆故障', '车辆故障')], max_length=10, verbose_name='安全分类')),
                ('todaytime', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('file', models.FileField(blank=True, null=True, upload_to='attachment/%Y-%m-%d/', verbose_name='附件')),
                ('chejian', models.IntegerField(choices=[(1, '修配车间'), (2, '修车车间')], verbose_name='车间')),
            ],
        ),
    ]
