# Generated by Django 5.0.4 on 2025-04-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory', models.CharField(choices=[('本段', '本段'), ('贵厂', '贵厂'), ('成都北', '成都北')], max_length=20, verbose_name='段名称')),
                ('old_axle_D', models.IntegerField(default=0, verbose_name='旧轴D')),
                ('old_axle_E', models.IntegerField(default=0, verbose_name='旧轴E')),
                ('old_wheel_D', models.IntegerField(default=0, verbose_name='旧轮D')),
                ('old_wheel_E', models.IntegerField(default=0, verbose_name='旧轮E')),
                ('new_axle_D', models.IntegerField(default=0, verbose_name='新轴D')),
                ('new_axle_E', models.IntegerField(default=0, verbose_name='新轴E')),
                ('new_wheel_D', models.IntegerField(default=0, verbose_name='新轮D')),
                ('new_wheel_E', models.IntegerField(default=0, verbose_name='新轮E')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory', models.CharField(blank=True, choices=[('贵厂', '贵厂'), ('成都北', '成都北')], max_length=20, null=True, verbose_name='段名称')),
                ('operation_type', models.CharField(choices=[('本段调出', '本段调出'), ('调入本段', '调入本段'), ('检修新品消耗', '检修新品消耗')], max_length=20, verbose_name='操作类型')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('old_axle_D_a', models.IntegerField(default=0, verbose_name='旧轴D')),
                ('old_axle_E_a', models.IntegerField(default=0, verbose_name='旧轴E')),
                ('old_wheel_D_a', models.IntegerField(default=0, verbose_name='旧轮D')),
                ('old_wheel_E_a', models.IntegerField(default=0, verbose_name='旧轮E')),
                ('new_axle_D_a', models.IntegerField(default=0, verbose_name='新轴D')),
                ('new_axle_E_a', models.IntegerField(default=0, verbose_name='新轴E')),
                ('new_wheel_D_a', models.IntegerField(default=0, verbose_name='新轮D')),
                ('new_wheel_E_a', models.IntegerField(default=0, verbose_name='新轮E')),
                ('old_axle_D_b', models.IntegerField(default=0, verbose_name='旧轴D')),
                ('old_axle_E_b', models.IntegerField(default=0, verbose_name='旧轴E')),
                ('old_wheel_D_b', models.IntegerField(default=0, verbose_name='旧轮D')),
                ('old_wheel_E_b', models.IntegerField(default=0, verbose_name='旧轮E')),
                ('new_axle_D_b', models.IntegerField(default=0, verbose_name='新轴D')),
                ('new_axle_E_b', models.IntegerField(default=0, verbose_name='新轴E')),
                ('new_wheel_D_b', models.IntegerField(default=0, verbose_name='新轮D')),
                ('new_wheel_E_b', models.IntegerField(default=0, verbose_name='新轮E')),
                ('old_axle_D_c', models.IntegerField(default=0, verbose_name='旧轴D')),
                ('old_axle_E_c', models.IntegerField(default=0, verbose_name='旧轴E')),
                ('old_wheel_D_c', models.IntegerField(default=0, verbose_name='旧轮D')),
                ('old_wheel_E_c', models.IntegerField(default=0, verbose_name='旧轮E')),
                ('new_axle_D_c', models.IntegerField(default=0, verbose_name='新轴D')),
                ('new_axle_E_c', models.IntegerField(default=0, verbose_name='新轴E')),
                ('new_wheel_D_c', models.IntegerField(default=0, verbose_name='新轮D')),
                ('new_wheel_E_c', models.IntegerField(default=0, verbose_name='新轮E')),
            ],
        ),
    ]
