# Generated by Django 5.0.4 on 2025-04-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldlcsl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrecord',
            name='new_axle_D_a',
            field=models.IntegerField(blank=True, default=0, verbose_name='新轴D'),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='new_axle_E_a',
            field=models.IntegerField(blank=True, default=0, verbose_name='新轴E'),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='new_wheel_D_a',
            field=models.IntegerField(blank=True, default=0, verbose_name='新轮D'),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='new_wheel_E_a',
            field=models.IntegerField(blank=True, default=0, verbose_name='新轮E'),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='old_axle_D_a',
            field=models.IntegerField(blank=True, default=0, verbose_name='旧轴D'),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='old_axle_E_a',
            field=models.IntegerField(blank=True, default=0, verbose_name='旧轴E'),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='old_wheel_D_a',
            field=models.IntegerField(blank=True, default=0, verbose_name='旧轮D'),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='old_wheel_E_a',
            field=models.IntegerField(blank=True, default=0, verbose_name='旧轮E'),
        ),
    ]
