# Generated by Django 5.0.4 on 2025-04-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldlcsl', '0003_alter_inventoryrecord_new_axle_d_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='new_axle_D',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='new_axle_E',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='new_wheel_D',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='new_wheel_E',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='old_axle_D',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='old_axle_E',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='old_wheel_D',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='old_wheel_E',
        ),
        migrations.AddField(
            model_name='inventory',
            name='initial_new_axle_D',
            field=models.IntegerField(default=0, verbose_name='初始新轴D'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='initial_new_axle_E',
            field=models.IntegerField(default=0, verbose_name='初始新轴E'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='initial_new_wheel_D',
            field=models.IntegerField(default=0, verbose_name='初始新轮D'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='initial_new_wheel_E',
            field=models.IntegerField(default=0, verbose_name='初始新轮E'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='initial_old_axle_D',
            field=models.IntegerField(default=0, verbose_name='初始旧轴D'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='initial_old_axle_E',
            field=models.IntegerField(default=0, verbose_name='初始旧轴E'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='initial_old_wheel_D',
            field=models.IntegerField(default=0, verbose_name='初始旧轮D'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='initial_old_wheel_E',
            field=models.IntegerField(default=0, verbose_name='初始旧轮E'),
        ),
    ]
