# Generated by Django 5.0.4 on 2025-04-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldlcsl', '0004_remove_inventory_new_axle_d_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='factory',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='initial_new_axle_D',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='initial_new_axle_E',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='initial_new_wheel_D',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='initial_new_wheel_E',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='initial_old_axle_D',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='initial_old_axle_E',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='initial_old_wheel_D',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='initial_old_wheel_E',
        ),
        migrations.AddField(
            model_name='inventory',
            name='new_axle_D_a',
            field=models.IntegerField(default=0, verbose_name='新轴D'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='new_axle_D_b',
            field=models.IntegerField(default=0, verbose_name='新轴D'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='new_axle_D_c',
            field=models.IntegerField(default=0, verbose_name='新轴D'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='new_axle_E_a',
            field=models.IntegerField(default=0, verbose_name='新轴E'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='new_axle_E_b',
            field=models.IntegerField(default=0, verbose_name='新轴E'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='new_axle_E_c',
            field=models.IntegerField(default=0, verbose_name='新轴E'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='new_wheel_D_a',
            field=models.IntegerField(default=0, verbose_name='新轮D'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='new_wheel_D_b',
            field=models.IntegerField(default=0, verbose_name='新轮D'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='new_wheel_D_c',
            field=models.IntegerField(default=0, verbose_name='新轮D'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='new_wheel_E_a',
            field=models.IntegerField(default=0, verbose_name='新轮E'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='new_wheel_E_b',
            field=models.IntegerField(default=0, verbose_name='新轮E'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='new_wheel_E_c',
            field=models.IntegerField(default=0, verbose_name='新轮E'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='old_axle_D_a',
            field=models.IntegerField(default=0, verbose_name='旧轴D'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='old_axle_D_b',
            field=models.IntegerField(default=0, verbose_name='旧轴D'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='old_axle_D_c',
            field=models.IntegerField(default=0, verbose_name='旧轴D'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='old_axle_E_a',
            field=models.IntegerField(default=0, verbose_name='旧轴E'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='old_axle_E_b',
            field=models.IntegerField(default=0, verbose_name='旧轴E'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='old_axle_E_c',
            field=models.IntegerField(default=0, verbose_name='旧轴E'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='old_wheel_D_a',
            field=models.IntegerField(default=0, verbose_name='旧轮D'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='old_wheel_D_b',
            field=models.IntegerField(default=0, verbose_name='旧轮D'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='old_wheel_D_c',
            field=models.IntegerField(default=0, verbose_name='旧轮D'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='old_wheel_E_a',
            field=models.IntegerField(default=0, verbose_name='旧轮E'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='old_wheel_E_b',
            field=models.IntegerField(default=0, verbose_name='旧轮E'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='old_wheel_E_c',
            field=models.IntegerField(default=0, verbose_name='旧轮E'),
        ),
    ]
