# Generated by Django 5.0.4 on 2025-10-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldlcsl', '0005_remove_inventory_factory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='new_axle_D_a',
            field=models.IntegerField(default=0, verbose_name='本段新轴D'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='new_axle_D_b',
            field=models.IntegerField(default=0, verbose_name='贵厂新轴D'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='new_axle_D_c',
            field=models.IntegerField(default=0, verbose_name='成都北新轴D'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='new_axle_E_a',
            field=models.IntegerField(default=0, verbose_name='本段新轴E'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='new_axle_E_b',
            field=models.IntegerField(default=0, verbose_name='贵厂新轴E'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='new_axle_E_c',
            field=models.IntegerField(default=0, verbose_name='成都北新轴E'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='new_wheel_D_a',
            field=models.IntegerField(default=0, verbose_name='本段新轮D'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='new_wheel_D_b',
            field=models.IntegerField(default=0, verbose_name='贵厂新轮D'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='new_wheel_D_c',
            field=models.IntegerField(default=0, verbose_name='成都北新轮D'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='new_wheel_E_a',
            field=models.IntegerField(default=0, verbose_name='本段新轮E'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='new_wheel_E_b',
            field=models.IntegerField(default=0, verbose_name='贵厂新轮E'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='new_wheel_E_c',
            field=models.IntegerField(default=0, verbose_name='成都北新轮E'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='old_axle_D_a',
            field=models.IntegerField(default=0, verbose_name='本段旧轴D'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='old_axle_D_b',
            field=models.IntegerField(default=0, verbose_name='贵厂旧轴D'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='old_axle_D_c',
            field=models.IntegerField(default=0, verbose_name='成都北旧轴D'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='old_axle_E_a',
            field=models.IntegerField(default=0, verbose_name='本段旧轴E'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='old_axle_E_b',
            field=models.IntegerField(default=0, verbose_name='贵厂旧轴E'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='old_axle_E_c',
            field=models.IntegerField(default=0, verbose_name='成都北旧轴E'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='old_wheel_D_a',
            field=models.IntegerField(default=0, verbose_name='本段旧轮D'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='old_wheel_D_b',
            field=models.IntegerField(default=0, verbose_name='贵厂旧轮D'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='old_wheel_D_c',
            field=models.IntegerField(default=0, verbose_name='成都北旧轮D'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='old_wheel_E_a',
            field=models.IntegerField(default=0, verbose_name='本段旧轮E'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='old_wheel_E_b',
            field=models.IntegerField(default=0, verbose_name='贵厂旧轮E'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='old_wheel_E_c',
            field=models.IntegerField(default=0, verbose_name='成都北旧轮E'),
        ),
        migrations.AlterField(
            model_name='inventoryrecord',
            name='operation_type',
            field=models.CharField(choices=[('本段调出', '本段调出'), ('调入本段', '调入本段'), ('检修新品消耗', '检修新品消耗'), ('报废', '报废')], max_length=20, verbose_name='操作类型'),
        ),
    ]
