# Generated by Django 5.0.4 on 2026-02-11 18:33

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dangjiantext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banzu', models.IntegerField(choices=[(1, '架车班党支部'), (2, '轮轴班党支部'), (3, '台车班党支部'), (4, '内制动班党支部'), (5, '外制动班党支部'), (6, '车钩班党支部'), (7, '探伤班党支部'), (8, '预修班党支部'), (9, '车体班党支部'), (10, '调车组党支部'), (12, '信息班党支部'), (15, '修配党支部'), (16, '修车党支部')], verbose_name='班组')),
                ('neirong', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='其他公示')),
                ('jieshao', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='党支部介绍')),
            ],
        ),
        migrations.CreateModel(
            name='dangyuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banzu', models.IntegerField(choices=[(1, '架车班党支部'), (2, '轮轴班党支部'), (3, '台车班党支部'), (4, '内制动班党支部'), (5, '外制动班党支部'), (6, '车钩班党支部'), (7, '探伤班党支部'), (8, '调车组党支部'), (9, '车体班党支部'), (10, '预修班党支部'), (12, '信息班党支部')], verbose_name='班组')),
                ('name', models.TextField(verbose_name='姓名')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('retire', models.IntegerField(choices=[(1, '在职'), (2, '退休')], default=1, verbose_name='在职/退休')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='出生年月')),
                ('join', models.DateField(blank=True, null=True, verbose_name='入党时间')),
                ('position', models.TextField(blank=True, null=True, verbose_name='职务')),
                ('number', models.TextField(blank=True, null=True, verbose_name='联系电话')),
                ('jiangcheng', models.TextField(blank=True, null=True, verbose_name='奖惩情况')),
                ('nationality', models.TextField(blank=True, null=True, verbose_name='民族')),
                ('zerengang', models.TextField(blank=True, null=True, verbose_name='责任岗')),
                ('zerenqu', models.TextField(blank=True, null=True, verbose_name='责任区')),
                ('time', models.DateField(blank=True, null=True, verbose_name='工作时间')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='', verbose_name='党员照片')),
            ],
        ),
        migrations.CreateModel(
            name='dangyuancgjq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banzu', models.IntegerField(choices=[(1, '架车班党支部'), (2, '轮轴班党支部'), (3, '台车班党支部'), (4, '内制动班党支部'), (5, '外制动班党支部'), (6, '车钩班党支部'), (7, '探伤班党支部'), (8, '预修班党支部'), (9, '车体班党支部'), (10, '调车组党支部'), (12, '信息班党支部')], verbose_name='班组')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('quarter', models.IntegerField(choices=[(1, '一季度'), (2, '二季度'), (3, '三季度'), (4, '四季度')], verbose_name='季度')),
                ('zerengang', models.IntegerField(blank=True, choices=[(1, '先锋岗'), (2, '达标岗'), (3, '警示岗')], null=True, verbose_name='责任岗')),
                ('zerenqu', models.IntegerField(blank=True, choices=[(1, '红旗区'), (2, '达标区'), (3, '警示区')], null=True, verbose_name='责任区')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djgl.dangyuan')),
            ],
        ),
        migrations.CreateModel(
            name='dangyuanindex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chejian', models.IntegerField(choices=[(1, '修配车间'), (2, '修车车间')], verbose_name='车间')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('quarter', models.IntegerField(choices=[(1, '一季度'), (2, '二季度'), (3, '三季度'), (4, '四季度')], verbose_name='季度')),
                ('hongqiqu', models.TextField(blank=True, null=True, verbose_name='红旗区')),
                ('dabiaoqu', models.TextField(blank=True, null=True, verbose_name='达标区')),
                ('jingshiqu', models.TextField(blank=True, null=True, verbose_name='警示区')),
                ('xianfenggang', models.TextField(blank=True, null=True, verbose_name='先锋岗')),
                ('dabiaogang', models.TextField(blank=True, null=True, verbose_name='达标岗')),
                ('jingshigang', models.TextField(blank=True, null=True, verbose_name='警示岗')),
                ('siyoudangyuan', models.TextField(blank=True, null=True, verbose_name='四优党员')),
                ('anquanzhixing', models.TextField(blank=True, null=True, verbose_name='安全之星')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djgl.dangyuan')),
            ],
        ),
        migrations.CreateModel(
            name='dangyuanjifen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banzu', models.IntegerField(choices=[(1, '架车班党支部'), (2, '轮轴班党支部'), (3, '台车班党支部'), (4, '内制动班党支部'), (5, '外制动班党支部'), (6, '车钩班党支部'), (7, '探伤班党支部'), (8, '预修班党支部'), (9, '车体班党支部'), (10, '调车组党支部'), (12, '信息班党支部')], verbose_name='班组')),
                ('jifen', models.IntegerField(blank=True, null=True, verbose_name='党员积分')),
                ('time', models.DateField(blank=True, null=True, verbose_name='时间')),
                ('zzsz', models.CharField(blank=True, max_length=200, null=True, verbose_name='政治素质')),
                ('ywjn', models.CharField(blank=True, max_length=200, null=True, verbose_name='业务技能')),
                ('gzyj', models.CharField(blank=True, max_length=200, null=True, verbose_name='工作业绩')),
                ('lxqz', models.CharField(blank=True, max_length=200, null=True, verbose_name='联系群众')),
                ('jfxd', models.CharField(blank=True, max_length=200, null=True, verbose_name='加分项点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djgl.dangyuan')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'time'], name='djgl_dangyu_user_id_5d84e4_idx')],
            },
        ),
    ]
