# Generated by Django 5.0.4 on 2026-02-11 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JkrqList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='姓名')),
                ('banzu', models.IntegerField(choices=[(1, '架车班'), (2, '轮轴班'), (3, '台车班'), (4, '内制动班'), (5, '外制动班'), (6, '车钩班'), (7, '探伤班'), (8, '调车组'), (9, '车体班'), (10, '预修班'), (12, '信息班'), (13, '干部')], verbose_name='班组')),
                ('people_type', models.CharField(choices=[('JKWH', '健康危害风险人员'), ('XNXGJB', '心脑血管疾病风险人员')], default='JKWH', max_length=20, verbose_name='分类')),
                ('people_level', models.CharField(choices=[('lv4', '高危'), ('lv3', '三类'), ('lv2', '二类（重点）'), ('lv1', '二类'), ('lv0', '一类')], max_length=20, verbose_name='等级')),
                ('people_height', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='身高')),
                ('people_weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='体重')),
                ('people_bmi', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='体重指数')),
                ('people_smoke', models.CharField(blank=True, choices=[('1', '否'), ('2', '是')], max_length=20, null=True, verbose_name='是否吸烟')),
                ('people_blood_fat', models.CharField(blank=True, choices=[('1', '异常'), ('0', '良好')], max_length=20, null=True, verbose_name='血脂异常')),
                ('people_blood_candy', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='血糖')),
                ('people_blood_high', models.CharField(blank=True, max_length=3, null=True, verbose_name='收缩压')),
                ('people_blood_low', models.CharField(blank=True, max_length=3, null=True, verbose_name='舒张压')),
                ('people_check_method', models.CharField(choices=[('DAYLY', '每日监测'), ('WEEKLY', '每周监测'), ('MONTHLY', '每月监测'), ('QUARTER', '每季度监测')], max_length=20, verbose_name='维护方式')),
                ('time', models.DateField(blank=True, null=True, verbose_name='时间')),
            ],
        ),
        migrations.CreateModel(
            name='JkrqList1Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banzu', models.IntegerField(choices=[(1, '架车班'), (2, '轮轴班'), (3, '台车班'), (4, '内制动班'), (5, '外制动班'), (6, '车钩班'), (7, '探伤班'), (8, '调车组'), (9, '车体班'), (10, '预修班'), (12, '信息班'), (13, '干部')], verbose_name='班组')),
                ('check_date', models.DateField(auto_now_add=True, verbose_name='检测日期')),
                ('people_blood_candy', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='血糖')),
                ('people_blood_high', models.CharField(blank=True, max_length=3, null=True, verbose_name='收缩压')),
                ('people_blood_low', models.CharField(blank=True, max_length=3, null=True, verbose_name='舒张压')),
                ('people_weight', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='体重')),
                ('people_bmi', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='体重指数')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='blood/%Y/%m/%d/', verbose_name='血压检测照片')),
                ('people', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jkrq.jkrqlist')),
            ],
        ),
    ]
