# Generated by Django 5.0.4 on 2026-03-23 15:07

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chejian', models.IntegerField(choices=[(0, '管理员'), (1, '修配车间'), (2, '修车车间')], verbose_name='车间')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('banzu', models.IntegerField(choices=[(1, '架车班'), (2, '轮轴班'), (3, '台车班'), (4, '内制动班'), (5, '外制动班'), (6, '车钩班'), (7, '探伤班'), (8, '调车组'), (9, '车体班'), (10, '预修班'), (12, '信息班'), (13, '干部')], verbose_name='班组')),
                ('role', models.CharField(choices=[('role1', '总管理员'), ('role2', '架车班'), ('role3', '轮轴班'), ('role4', '台车班'), ('role5', '架车班手持机'), ('role6', '轮轴班手持机'), ('role7', '调度员'), ('role8', '安全员'), ('role9', '技术员'), ('role10', '内制动班'), ('role11', '外制动班'), ('role12', '车钩班'), ('role13', '探伤班'), ('role14', '调车组'), ('role15', '车体班'), ('role16', '预修班'), ('role18', '信息班'), ('role19', '修配管理员'), ('role20', '修车管理员')], max_length=32, verbose_name='角色')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='超级用户状态')),
            ],
        ),
        migrations.CreateModel(
            name='bogie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taiwei', models.SmallIntegerField(choices=[(1, '7-1'), (2, '7-2'), (3, '7-3'), (4, '7-4'), (5, '7-5'), (6, '7-6'), (7, '7-7'), (8, '7-8'), (9, '7-9'), (10, '8-1'), (11, '8-2'), (12, '8-3'), (13, '8-4'), (14, '8-5'), (15, '8-6'), (16, '8-7'), (17, '8-8'), (18, '8-9'), (19, '9-1'), (20, '9-2'), (21, '9-3'), (22, '9-4'), (23, '9-5'), (24, '9-6'), (25, '9-7'), (26, '9-8'), (27, '9-9')], verbose_name='台位顺序')),
                ('shunxu', models.SmallIntegerField(choices=[(1, '一次入库'), (2, '二次入库'), (3, '三次入库')], verbose_name='出车顺序')),
                ('dianban1', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(60)], verbose_name='一位垫板')),
                ('dianban2', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(60)], verbose_name='二位垫板')),
                ('lunjing1', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(750), django.core.validators.MaxValueValidator(850)], verbose_name='一位轮径')),
                ('lunjing2', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(750), django.core.validators.MaxValueValidator(850)], verbose_name='二位轮径')),
                ('lunjing3', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(750), django.core.validators.MaxValueValidator(850)], verbose_name='三位轮径')),
                ('lunjing4', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(750), django.core.validators.MaxValueValidator(850)], verbose_name='四位轮径')),
                ('todaytime', models.DateTimeField(verbose_name='日期')),
                ('is_updated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='initial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todaytime', models.DateTimeField(verbose_name='日期')),
                ('taiwei', models.SmallIntegerField(choices=[(1, '7-1'), (2, '7-2'), (3, '7-3'), (4, '7-4'), (5, '7-5'), (6, '7-6'), (7, '7-7'), (8, '7-8'), (9, '7-9'), (10, '8-1'), (11, '8-2'), (12, '8-3'), (13, '8-4'), (14, '8-5'), (15, '8-6'), (16, '8-7'), (17, '8-8'), (18, '8-9'), (19, '9-1'), (20, '9-2'), (21, '9-3'), (22, '9-4'), (23, '9-5'), (24, '9-6'), (25, '9-7'), (26, '9-8'), (27, '9-9')], verbose_name='台位顺序')),
                ('shunxu', models.SmallIntegerField(choices=[(1, '一次入库'), (2, '二次入库'), (3, '三次入库')], verbose_name='进车顺序')),
                ('chegou1', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(850), django.core.validators.MaxValueValidator(999)], verbose_name='一位钩高')),
                ('chegou2', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(850), django.core.validators.MaxValueValidator(999)], verbose_name='二位钩高')),
                ('dianban1', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='一位垫板')),
                ('dianban2', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='二位垫板')),
                ('lunjing1', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(750), django.core.validators.MaxValueValidator(850)], verbose_name='一位轮径')),
                ('lunjing2', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(750), django.core.validators.MaxValueValidator(850)], verbose_name='二位轮径')),
                ('lunjing3', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(750), django.core.validators.MaxValueValidator(850)], verbose_name='三位轮径')),
                ('lunjing4', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(750), django.core.validators.MaxValueValidator(850)], verbose_name='四位轮径')),
                ('pangcheng1', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(35)], verbose_name='一位上旁承')),
                ('pangcheng2', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(35)], verbose_name='二位上旁承')),
                ('xiucheng', models.CharField(blank=True, choices=[('段', '段'), ('厂', '厂'), ('临', '临')], default='段', max_length=10, null=True, verbose_name='货车修程')),
                ('chexing', models.CharField(blank=True, max_length=20, null=True, verbose_name='车种车型')),
                ('nianxian', models.SmallIntegerField(blank=True, choices=[(4, '0.8'), (5, '0.9'), (6, '0.10'), (7, '0.11'), (1, '1'), (8, '1.1'), (9, '1.2'), (10, '1.3'), (11, '1.4'), (12, '1.5'), (2, '1.6'), (13, '1.7'), (14, '1.8'), (15, '1.9'), (16, '1.10'), (17, '1.11'), (3, '2'), (18, '2.1'), (19, '2.2'), (20, '2.3'), (21, '2.4'), (22, '2.5')], null=True, verbose_name='轮对年限')),
                ('beizhu', models.SmallIntegerField(blank=True, choices=[(1, '放7-1前'), (2, '放7-2前'), (3, '放7-3前'), (4, '放7-4前'), (5, '放7-5前'), (6, '放7-6前'), (7, '放7-7前'), (8, '放7-8前'), (9, '放7-9前'), (10, '放7-9后'), (11, '放8-1前'), (12, '放8-2前'), (13, '放8-3前'), (14, '放8-4前'), (15, '放8-5前'), (16, '放8-6前'), (17, '放8-7前'), (18, '放8-8前'), (19, '放8-9前'), (20, '放8-9后'), (21, '放9-1前'), (22, '放9-2前'), (23, '放9-3前'), (24, '放9-4前'), (25, '放9-5前'), (26, '放9-6前'), (27, '放9-7前'), (28, '放9-8前'), (29, '放9-9前'), (30, '放9-9后')], null=True, verbose_name='临时出车顺序')),
                ('is_updated', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gudao1', models.SmallIntegerField(choices=[(9, '9道'), (8, '8道'), (7, '7道')], verbose_name='第一线')),
                ('gudao2', models.SmallIntegerField(choices=[(7, '7道'), (8, '8道'), (9, '9道')], verbose_name='第二线')),
                ('gudao3', models.SmallIntegerField(choices=[(8, '8道'), (7, '7道'), (9, '9道')], verbose_name='第三线')),
                ('todaytime', models.DateTimeField(verbose_name='日期')),
            ],
        ),
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guotie1', models.IntegerField(blank=True, null=True, verbose_name='年度国铁厂修总任务')),
                ('guotie2', models.IntegerField(blank=True, null=True, verbose_name='年度国铁厂修已完成')),
                ('guotie3', models.IntegerField(blank=True, null=True, verbose_name='年度自备厂修已完成')),
                ('guotie7', models.IntegerField(blank=True, null=True, verbose_name='年度自备厂修总任务')),
                ('guotie4', models.IntegerField(blank=True, null=True, verbose_name='年度国铁段修总任务')),
                ('guotie5', models.IntegerField(blank=True, null=True, verbose_name='年度国铁段修已完成')),
                ('guotie6', models.IntegerField(blank=True, null=True, verbose_name='年度自备段修已完成')),
                ('guotie8', models.IntegerField(blank=True, null=True, verbose_name='年度自备段修总任务')),
                ('pengche1', models.IntegerField(blank=True, null=True, verbose_name='棚车适应改造总任务')),
                ('pengche2', models.IntegerField(blank=True, null=True, verbose_name='棚车适应改造已完成')),
                ('pengche3', models.IntegerField(blank=True, null=True, verbose_name='棚车门锁改造总任务')),
                ('pengche4', models.IntegerField(blank=True, null=True, verbose_name='棚车门锁改造已完成')),
                ('changche1', models.IntegerField(blank=True, null=True, verbose_name='敞车门锁改造总任务')),
                ('changche2', models.IntegerField(blank=True, null=True, verbose_name='敞车门锁改造已完成')),
                ('duanxiu1', models.IntegerField(blank=True, null=True, verbose_name='月计划国铁段修总任务')),
                ('duanxiu2', models.IntegerField(blank=True, null=True, verbose_name='月完成国铁段修总任务')),
                ('duanxiu3', models.IntegerField(blank=True, null=True, verbose_name='月计划局管内用车段修')),
                ('duanxiu4', models.IntegerField(blank=True, null=True, verbose_name='月完成局管内用车段修')),
                ('duanxiu5', models.IntegerField(blank=True, null=True, verbose_name='月计划自备段修')),
                ('duanxiu6', models.IntegerField(blank=True, null=True, verbose_name='月完成自备段修')),
                ('changxiu1', models.IntegerField(blank=True, null=True, verbose_name='月计划国铁厂修')),
                ('changxiu2', models.IntegerField(blank=True, null=True, verbose_name='月完成国铁厂修')),
                ('changxiu3', models.IntegerField(blank=True, null=True, verbose_name='月计划自备厂修')),
                ('changxiu4', models.IntegerField(blank=True, null=True, verbose_name='月完成自备厂修')),
                ('heji1', models.IntegerField(blank=True, null=True, verbose_name='月计划合计')),
                ('heji2', models.IntegerField(blank=True, null=True, verbose_name='月完成合计')),
                ('diban1', models.IntegerField(blank=True, null=True, verbose_name='月度复合地板')),
                ('diban2', models.IntegerField(blank=True, null=True, verbose_name='年度复合地板')),
                ('TgaiK', models.IntegerField(blank=True, null=True, verbose_name='T改K')),
                ('linxiu', models.IntegerField(blank=True, null=True, verbose_name='月计划临修车')),
                ('linxiu1', models.IntegerField(blank=True, null=True, verbose_name='月完成临修车')),
                ('zhengzhi', models.IntegerField(blank=True, null=True, verbose_name='木地板专项修')),
                ('JSQ', models.IntegerField(blank=True, null=True, verbose_name='年度JSQ段修完成总数')),
                ('time1', models.DateTimeField(blank=True, null=True, verbose_name='劳动安全开始时间')),
                ('time2', models.DateTimeField(blank=True, null=True, verbose_name='行车安全开始时间')),
                ('time3', models.DateTimeField(blank=True, null=True, verbose_name='车辆故障开始时间')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiwubiaoti', models.TextField(verbose_name='重要事务标题')),
                ('user', models.TextField(blank=True, null=True, verbose_name='发布人')),
                ('shiwuneirong', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='重要事务内容')),
                ('todaytime', models.DateTimeField(verbose_name='日期')),
                ('chejian', models.IntegerField(choices=[(1, '修配车间'), (2, '修车车间')], verbose_name='车间')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionReads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.admin')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.transactions')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachment/%Y-%m-%d/', verbose_name='附件')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app01.transactions')),
            ],
        ),
    ]
