# Generated by Django 5.0.4 on 2026-03-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='initial',
            name='car_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='车号'),
        ),
    ]
