# Generated by Django 5.0.4 on 2026-02-11 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('banzu', models.IntegerField(blank=True, choices=[(1, '架车班'), (2, '轮轴班'), (3, '台车班'), (4, '内制动班'), (5, '外制动班'), (6, '车钩班'), (7, '探伤班'), (8, '调车组'), (9, '车体班'), (10, '预修班'), (12, '信息班'), (15, '修配日勤'), (16, '修车日勤')], null=True, verbose_name='班组')),
                ('chejian', models.IntegerField(blank=True, choices=[(1, '修配车间'), (2, '修车车间')], null=True, verbose_name='车间')),
                ('gongzhong', models.CharField(max_length=100)),
                ('gonghao', models.CharField(max_length=100)),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('total_days', models.IntegerField(verbose_name='打分总天数')),
                ('main_area_days', models.IntegerField(verbose_name='本工区打分天数')),
                ('other_area_days', models.IntegerField(verbose_name='其他工区打分天数')),
                ('base_coefficient', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='个人挂钩基数')),
                ('start_score', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='起始分')),
                ('main_area_score', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='本工区定额所得分')),
                ('main_area_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='本工区定额所得金额')),
                ('other_area_score', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='其他工区定额所得分')),
                ('other_area_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='其他工区定额所得金额')),
                ('status', models.CharField(max_length=50, verbose_name='考核状态')),
                ('remarks', models.TextField(blank=True, verbose_name='不参与积分备注说明')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gongzhong', models.CharField(blank=True, max_length=100, null=True)),
                ('gonghao', models.CharField(blank=True, max_length=50, null=True)),
                ('banzu', models.IntegerField(blank=True, choices=[(1, '架车班'), (2, '轮轴班'), (3, '台车班'), (4, '内制动班'), (5, '外制动班'), (6, '车钩班'), (7, '探伤班'), (8, '调车组'), (9, '车体班'), (10, '预修班'), (12, '信息班'), (15, '修配日勤'), (16, '修车日勤')], null=True, verbose_name='班组')),
                ('chejian', models.IntegerField(blank=True, choices=[(1, '修配车间'), (2, '修车车间')], null=True, verbose_name='车间')),
                ('created_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('work_score', models.FloatField(default=0)),
                ('study_score', models.FloatField(default=0)),
                ('business_score', models.FloatField(default=0)),
                ('holiday_score', models.FloatField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gfcx.employee')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
