"""
Django settings for djangoProject project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

import app01
import xfgl
import jkrq
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_sqqcfsf5jwn+77q=6=nvby@tn)b!7e=vuad+_*j%8c!&glpl#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

LOGGING = {  # 创建一个名为LOGGING的字典来保存日志配置.
    'version': 1,  # 日志配置的版本，当前版本是1.

    'disable_existing_loggers': False,  # 是否禁用已经存在的日志器，设为False表示不禁用.

    'handlers': {  # 定义一些处理程序，这些处理程序决定如何处理日志消息。一般包括控制台处理程序和文件处理程序
        'file': {  # 这是文件处理程序，名为'file'
            'level': 'INFO',  # 这是日志等级，'DEBUG'是最低的级别，它会捕获所有的日志消息。其他的级别有'INFO', 'WARNING', 'ERROR' 和 'CRITICAL'
            'class': 'logging.FileHandler',  # 使用的处理器类。文件处理程序使用 Python 的内置 'logging.FileHandler' 类
            'filename': 'django_debug.log',  # 这个处理程序将日志消息写入的文件名.
        },
    },

    'root': {  # root 日志器, 它会接收所有的日志消息，除非它们被其他日志器处理
        'handlers': ['file'],  # 此日志器使用名为 'file' 的处理程序
        'level': 'INFO',  # 此日志器的级别也设为 'INFO'
    },
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'templated_email',
    'app01.apps.App01Config',
    'xfgl.apps.XfglConfig',
    "jkrq.apps.JkrqConfig",
    "cjgj.apps.CjgjConfig",
    "djgl.apps.DjglConfig",
    "bzrz.apps.BzrzConfig",
    "ldlcsl.apps.LdlcslConfig",
    "meeting.apps.MeetingConfig",
    'ckeditor',
    'rest_framework',
    "wjcy.apps.WjcyConfig",
    "gfcx.apps.GfcxConfig",
    "aqts.apps.AqtsConfig",
    'tools.apps.ToolsAppConfig',
    # 车间设备监控大屏
    'workshop.apps.WorkshopConfig',
    # CORS支持
    'corsheaders',
]

TEMPLATED_EMAIL_BACKEND = 'templated_email.backends.vanilla_django.VanillaDjangoBackend'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS中间件，放在CommonMiddleware之前
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangoProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': []
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tools.context_processors.tools_context_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoProject.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "app01",
        "USER": "root",
        "PASSWORD": "6686258q",
        "HOST": "127.0.0.1",
        "PORT": "3306",
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    r'E:\lzznk\app01\static',
    r'E:\lzznk\tools\static',
    r'E:\lzznk\workshop\static',
]

# Authentication settings
LOGIN_URL = '/tools/login_tools/'
LOGIN_REDIRECT_URL = '/tools/dashboard/'
LOGOUT_REDIRECT_URL = '/tools/login_tools/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Absolute filesystem path to the directory that will hold user-uploaded files.
# Example: "/var/www/example.com/media/"
MEDIA_ROOT = 'E:/credential'

# URL that handles the media served from MEDIA_ROOT. Use a trailing slash if needed.
# Examples: "http://example.com/media/", "http://media.example.com/"
MEDIA_URL = 'media/'

# 自定义认证后端
AUTHENTICATION_BACKENDS = [
    'app01.backends.AdminAuthBackend',
    'tools.auth_backends.ToolsAuthBackend',  # Tools应用专用认证后端
    'django.contrib.auth.backends.ModelBackend',
]
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_CONFIGS = {
    'default': {
        'language': 'zh-cn',
        'toolbar': 'Custom',
        'width': '100%',
        'height': '400px',
        'removePlugins': 'stylesheetparser',
        'allowedContent': True,
        'toolbar_Custom': [
            {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
            {'name': 'basicstyles', 'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', 'RemoveFormat']},
            {'name': 'paragraph', 'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-']},
            {'name': 'links', 'items': ['Link', 'Unlink']},
            {'name': 'insert', 'items': ['Table', 'HorizontalRule', 'SpecialChar']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'tools', 'items': ['Maximize', 'ShowBlocks', '-', '-', 'Preview', 'Print']}
        ]
    }
}

SESSION_COOKIE_NAME = "sessionid_10003"

# CORS配置 - 允许Vue前端访问
CORS_ALLOW_ALL_ORIGINS = True  # 开发环境允许所有来源
CORS_ALLOW_CREDENTIALS = True

# REST Framework配置
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}