# Generated by Django 5.0.4 on 2026-02-11 18:33

import django.db.models.deletion
import django.utils.timezone
import wjcy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bzrz', '0002_alter_teamuser_banzu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circulates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('安全管理', '安全管理'), ('设备管理', '设备管理'), ('生产管理', '生产管理'), ('特种设备', '特种设备'), ('消防安全', '消防安全'), ('网络安全', '网络安全'), ('综合事务', '综合事务'), ('技术管理', '技术管理'), ('产品质量', '产品质量')], max_length=50, verbose_name='传阅分类')),
                ('title', models.CharField(max_length=100, verbose_name='传阅名称')),
                ('name', models.CharField(max_length=100, verbose_name='发布人')),
                ('key_remindertitle', models.CharField(blank=True, max_length=100, null=True, verbose_name='重点提示')),
                ('chejian', models.IntegerField(choices=[(1, '修配车间'), (2, '修车车间')], verbose_name='车间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布日期')),
                ('status', models.IntegerField(choices=[(0, '正在传阅'), (1, '已关闭传阅')], default=0, verbose_name='是否传阅')),
            ],
        ),
        migrations.CreateModel(
            name='CirculateReads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to=wjcy.models.get_photo_path, verbose_name='照片')),
                ('beizhu', models.CharField(blank=True, max_length=100, null=True, verbose_name='缺席原因')),
                ('read', models.BooleanField(default=False)),
                ('photo_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circulatephoto', to='bzrz.teamuser')),
                ('circulate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wjcy.circulates')),
            ],
        ),
        migrations.CreateModel(
            name='CirculateAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='wjcy/', verbose_name='附件')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('circulate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='wjcy.circulates')),
            ],
        ),
    ]
