# Generated by Django 5.0.4 on 2026-04-23 08:54

import django.db.models.deletion
import workshop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='区域名称')),
                ('pos_x', models.IntegerField(default=0, verbose_name='X坐标')),
                ('pos_y', models.IntegerField(default=0, verbose_name='Y坐标')),
                ('width', models.IntegerField(default=200, verbose_name='宽度')),
                ('height', models.IntegerField(default=150, verbose_name='高度')),
                ('color', models.CharField(default='rgba(52, 152, 219, 0.08)', max_length=50, verbose_name='背景色')),
                ('border_color', models.CharField(default='rgba(52, 152, 219, 0.3)', max_length=50, verbose_name='边框色')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '区域',
                'verbose_name_plural': '区域配置',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='如: detect, lathe', max_length=30, unique=True, verbose_name='类型代码')),
                ('name', models.CharField(help_text='如: 检测设备', max_length=50, verbose_name='类型名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '设备类型',
                'verbose_name_plural': '设备类型',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SchedulerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=50, verbose_name='任务ID')),
                ('job_name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('execute_time', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('is_work_time', models.BooleanField(default=False, verbose_name='是否工作时间')),
                ('success', models.BooleanField(default=False, verbose_name='执行成功')),
                ('message', models.TextField(blank=True, default='', verbose_name='执行结果')),
            ],
            options={
                'verbose_name': '定时任务日志',
                'verbose_name_plural': '定时任务日志',
                'ordering': ['-execute_time'],
            },
        ),
        migrations.CreateModel(
            name='SyncConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='配置名称')),
                ('api_url', models.CharField(max_length=500, verbose_name='API地址')),
                ('api_key', models.CharField(blank=True, default='', max_length=200, verbose_name='API密钥')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sync_interval', models.IntegerField(default=60, verbose_name='同步间隔(秒)')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='上次同步时间')),
                ('last_status', models.CharField(blank=True, default='', max_length=20, verbose_name='上次同步状态')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='上次错误信息')),
            ],
            options={
                'verbose_name': '同步配置',
                'verbose_name_plural': '同步配置',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=20, unique=True, verbose_name='设备编号')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='设备描述')),
                ('status', models.CharField(choices=[('running', '运行中'), ('fault', '故障'), ('offline', '离线')], default='offline', max_length=20, verbose_name='状态')),
                ('auto_status', models.BooleanField(default=True, help_text='启用后根据点检/维修记录自动判断状态，禁用则使用手动设置的状态', verbose_name='启用自动状态判断')),
                ('fault_time', models.DateTimeField(blank=True, null=True, verbose_name='故障发生时间')),
                ('inspection_start', models.DateTimeField(blank=True, null=True, verbose_name='开工点检时间')),
                ('inspection_end', models.DateTimeField(blank=True, null=True, verbose_name='完工点检时间')),
                ('inspection_location', models.CharField(blank=True, default='', max_length=100, verbose_name='设备处所')),
                ('pos_x', models.IntegerField(default=0, verbose_name='X坐标')),
                ('pos_y', models.IntegerField(default=0, verbose_name='Y坐标')),
                ('pos_width', models.IntegerField(default=100, verbose_name='宽度')),
                ('pos_height', models.IntegerField(default=60, verbose_name='高度')),
                ('qrcode_image', models.ImageField(blank=True, null=True, upload_to=workshop.models.qrcode_upload_path, verbose_name='设备二维码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('linked_device', models.ForeignKey(blank=True, help_text='设置后，本设备状态跟随该设备变化', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop.device', verbose_name='跟随设备')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop.devicearea', verbose_name='所属区域')),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop.devicetype', verbose_name='设备类型')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'ordering': ['device_id'],
            },
        ),
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=20, verbose_name='设备编号')),
                ('device_name', models.CharField(blank=True, default='', max_length=100, verbose_name='设备名称')),
                ('location', models.CharField(blank=True, default='', max_length=100, verbose_name='设备处所')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开工点检时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='完工点检时间')),
                ('record_date', models.DateField(db_index=True, help_text='同步的是哪一天的数据', verbose_name='记录日期')),
                ('sync_time', models.DateTimeField(auto_now=True, verbose_name='同步时间')),
            ],
            options={
                'verbose_name': '点检记录',
                'verbose_name_plural': '点检记录',
                'ordering': ['-start_time'],
                'unique_together': {('device_id', 'record_date')},
            },
        ),
        migrations.CreateModel(
            name='RepairRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=20, verbose_name='设备编号')),
                ('device_name', models.CharField(blank=True, default='', max_length=100, verbose_name='设备名称')),
                ('location', models.CharField(blank=True, default='', max_length=100, verbose_name='设备处所')),
                ('model', models.CharField(blank=True, default='', max_length=100, verbose_name='型号规格')),
                ('department', models.CharField(blank=True, default='', max_length=50, verbose_name='所在部门')),
                ('team_name', models.CharField(blank=True, default='', max_length=50, verbose_name='所在班组')),
                ('fault_date', models.DateTimeField(blank=True, null=True, verbose_name='故障日期')),
                ('reporter', models.CharField(blank=True, default='', max_length=50, verbose_name='发现人')),
                ('phenomenon', models.CharField(blank=True, default='', max_length=500, verbose_name='故障情况描述')),
                ('analysis', models.CharField(blank=True, default='', max_length=500, verbose_name='故障分析')),
                ('repair_date', models.DateTimeField(blank=True, null=True, verbose_name='维修日期')),
                ('repair_team', models.CharField(blank=True, default='', max_length=50, verbose_name='维修班组')),
                ('worker', models.CharField(blank=True, default='', max_length=50, verbose_name='修理人员')),
                ('result', models.CharField(blank=True, default='', max_length=500, verbose_name='故障处理情况')),
                ('materials', models.CharField(blank=True, default='', max_length=200, verbose_name='材料消耗')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否已修复')),
                ('external_id', models.IntegerField(blank=True, help_text='用于避免重复同步', null=True, verbose_name='外部记录ID')),
                ('record_date', models.DateField(db_index=True, help_text='同步的是哪一天的数据', verbose_name='记录日期')),
                ('sync_time', models.DateTimeField(auto_now=True, verbose_name='同步时间')),
            ],
            options={
                'verbose_name': '维修记录',
                'verbose_name_plural': '维修记录',
                'ordering': ['-fault_date'],
                'unique_together': {('device_id', 'record_date')},
            },
        ),
    ]
