# Generated by Django 5.0.4 on 2026-03-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=20, unique=True, verbose_name='设备编号')),
                ('name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('area', models.CharField(max_length=50, verbose_name='所属区域')),
                ('device_type', models.CharField(choices=[('measure', '测量设备'), ('press', '压装设备'), ('platform', '平台设备'), ('conveyor', '传输设备'), ('warehouse', '仓储设备'), ('cabinet', '控制设备'), ('room', '防护设施'), ('power', '动力设备')], default='measure', max_length=30, verbose_name='设备类型')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='设备描述')),
                ('status', models.CharField(choices=[('running', '运行中'), ('fault', '故障'), ('offline', '离线')], default='offline', max_length=20, verbose_name='状态')),
                ('fault_time', models.DateTimeField(blank=True, null=True, verbose_name='故障发生时间')),
                ('pos_x', models.IntegerField(default=0, verbose_name='X坐标')),
                ('pos_y', models.IntegerField(default=0, verbose_name='Y坐标')),
                ('pos_width', models.IntegerField(default=100, verbose_name='宽度')),
                ('pos_height', models.IntegerField(default=60, verbose_name='高度')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='总容量')),
                ('used', models.IntegerField(blank=True, null=True, verbose_name='已使用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'ordering': ['device_id'],
            },
        ),
        migrations.CreateModel(
            name='DeviceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='区域名称')),
                ('pos_x', models.IntegerField(default=0, verbose_name='X坐标')),
                ('pos_y', models.IntegerField(default=0, verbose_name='Y坐标')),
                ('width', models.IntegerField(default=200, verbose_name='宽度')),
                ('height', models.IntegerField(default=150, verbose_name='高度')),
                ('color', models.CharField(default='rgba(52, 152, 219, 0.08)', max_length=50, verbose_name='背景色')),
                ('border_color', models.CharField(default='rgba(52, 152, 219, 0.3)', max_length=50, verbose_name='边框色')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '区域',
                'verbose_name_plural': '区域配置',
                'ordering': ['sort_order'],
            },
        ),
    ]
