# Generated by Django 5.0.4 on 2026-03-23 09:50

import workshop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='qrcode_image',
            field=models.ImageField(blank=True, null=True, upload_to=workshop.models.qrcode_upload_path, verbose_name='设备二维码'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('grind', '磨合设备'), ('detect', '检测设备'), ('unload', '退卸设备'), ('rust', '除锈设备'), ('flaw', '探伤设备'), ('oil', '涂油设备'), ('bolt', '紧固设备'), ('press', '压装设备'), ('measure', '测量设备'), ('crane', '天车设备'), ('lathe', '车轮车床'), ('protect', '防护装置'), ('forklift', '货叉装置'), ('stacker', '堆垛系统'), ('warehouse', '立体库'), ('platform', '平台设备'), ('conveyor', '传输设备'), ('cabinet', '控制设备'), ('room', '防护设施'), ('power', '动力设备')], default='measure', max_length=30, verbose_name='设备类型'),
        ),
    ]
