# Generated by Django 5.0.4 on 2026-03-23

from django.db import migrations, models
import django.db.models.deletion


def create_device_types(apps, schema_editor):
    """创建设备类型初始数据"""
    DeviceType = apps.get_model('workshop', 'DeviceType')
    types_data = [
        ('grind', '磨合设备', 1),
        ('detect', '检测设备', 2),
        ('unload', '退卸设备', 3),
        ('rust', '除锈设备', 4),
        ('flaw', '探伤设备', 5),
        ('oil', '涂油设备', 6),
        ('bolt', '紧固设备', 7),
        ('press', '压装设备', 8),
        ('measure', '测量设备', 9),
        ('crane', '天车设备', 10),
        ('lathe', '车轮车床', 11),
        ('protect', '防护装置', 12),
        ('forklift', '货叉装置', 13),
        ('stacker', '堆垛系统', 14),
        ('warehouse', '立体库', 15),
        ('turntable', '转盘设备', 16),
    ]
    for code, name, sort_order in types_data:
        DeviceType.objects.create(code=code, name=name, sort_order=sort_order)


def create_device_areas(apps, schema_editor):
    """创建区域初始数据"""
    DeviceArea = apps.get_model('workshop', 'DeviceArea')
    areas_data = [
        ('轮轴间', 10, 40, 580, 540, 1),
        ('探伤间', 610, 40, 380, 540, 2),
        ('旋轮间', 1010, 40, 380, 540, 3),
        ('配件存放间', 0, 620, 250, 60, 4),
        ('工具间', 250, 620, 120, 50, 5),
        ('轴承端盖及配件清洗间', 50, 520, 160, 50, 6),
        ('探伤间休室', 220, 520, 170, 50, 7),
        ('轮轴间休室', 400, 520, 200, 50, 8),
        ('墙外', 0, 0, 0, 0, 99),
    ]
    for name, pos_x, pos_y, width, height, sort_order in areas_data:
        DeviceArea.objects.create(
            name=name, pos_x=pos_x, pos_y=pos_y,
            width=width, height=height, sort_order=sort_order
        )


def migrate_device_data(apps, schema_editor):
    """迁移设备数据到新的外键字段"""
    Device = apps.get_model('workshop', 'Device')
    DeviceType = apps.get_model('workshop', 'DeviceType')
    DeviceArea = apps.get_model('workshop', 'DeviceArea')

    type_mapping = {dt.code: dt for dt in DeviceType.objects.all()}
    area_mapping = {da.name: da for da in DeviceArea.objects.all()}

    for device in Device.objects.all():
        if device.device_type_code:
            device.device_type = type_mapping.get(device.device_type_code)
        if device.area_name:
            device.area = area_mapping.get(device.area_name)
        device.save()


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_device_qrcode_image_alter_device_device_type'),
    ]

    operations = [
        # 1. 创建DeviceType表
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='如: detect, lathe', max_length=30, unique=True, verbose_name='类型代码')),
                ('name', models.CharField(help_text='如: 检测设备', max_length=50, verbose_name='类型名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '设备类型',
                'verbose_name_plural': '设备类型',
                'ordering': ['sort_order', 'code'],
            },
        ),
        # 2. 添加临时字段保存旧数据
        migrations.AddField(
            model_name='device',
            name='device_type_code',
            field=models.CharField(max_length=30, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='area_name',
            field=models.CharField(max_length=50, blank=True, null=True),
        ),
        # 3. 复制旧数据到临时字段
        migrations.RunSQL(
            "UPDATE workshop_device SET device_type_code = device_type",
            "UPDATE workshop_device SET device_type = device_type_code"
        ),
        migrations.RunSQL(
            "UPDATE workshop_device SET area_name = area",
            "UPDATE workshop_device SET area = area_name"
        ),
        # 4. 删除旧的char字段，添加新的FK字段
        migrations.RemoveField(model_name='device', name='device_type'),
        migrations.RemoveField(model_name='device', name='area'),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop.devicetype', verbose_name='设备类型'),
        ),
        migrations.AddField(
            model_name='device',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop.devicearea', verbose_name='所属区域'),
        ),
        # 5. 创建初始数据
        migrations.RunPython(create_device_types),
        migrations.RunPython(create_device_areas),
        # 6. 迁移数据到新字段
        migrations.RunPython(migrate_device_data),
        # 7. 删除临时字段
        migrations.RemoveField(model_name='device', name='device_type_code'),
        migrations.RemoveField(model_name='device', name='area_name'),
    ]