# Generated by Django 5.0.4 on 2026-03-30 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_rename_team_repairrecord_repair_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='device',
            name='used',
        ),
    ]
