# Generated by Django 5.0.4 on 2026-03-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_remove_capacity_used_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='外部系统中的设备编号，用于匹配点检和维修数据', max_length=50, verbose_name='外部设备编号'),
        ),
    ]
