# Generated by Django 5.0.4 on 2026-03-31 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_add_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='external_id',
        ),
    ]
