# Generated by Django 5.0.4 on 2026-03-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0008_remove_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='auto_status',
            field=models.BooleanField(default=True, help_text='启用后根据点检/维修记录自动判断状态，禁用则使用手动设置的状态', verbose_name='启用自动状态判断'),
        ),
    ]
