# Generated by Django 5.0.4 on 2025-03-24 07:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.IntegerField(choices=[(1, '消火栓'), (2, '灭火器'), (3, '喷漆房'), (4, '集中供气'), (5, '液氧'), (6, '丙烷'), (7, '乙炔')], verbose_name='设备名')),
                ('number', models.CharField(blank=True, max_length=100, null=True, verbose_name='设备编号')),
                ('banzu', models.IntegerField(blank=True, choices=[(1, '架车班'), (2, '轮轴班'), (3, '台车班'), (4, '内制动班'), (5, '外制动班'), (6, '车钩班'), (7, '探伤班'), (8, '调车组'), (9, '车体班'), (10, '预修班'), (11, '质检组'), (12, '信息班')], null=True, verbose_name='所属班组')),
                ('type', models.IntegerField(choices=[(1, '气瓶'), (2, '喷漆房'), (3, '集中供气'), (4, '消防器材')], verbose_name='设备类型')),
                ('inspect', models.IntegerField(choices=[(1, '开工前和完工后点检'), (2, '每日巡检'), (3, '月度检查')], verbose_name='检查方式')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('production_time', models.DateField(blank=True, null=True, verbose_name='生产日期')),
                ('breakdown', models.IntegerField(choices=[(0, '正常'), (1, '故障')], default=0, verbose_name='是否故障')),
                ('reason', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='故障原因')),
                ('check_date', models.DateTimeField(blank=True, null=True, verbose_name='最近一次检查时间')),
                ('check_item1', models.CharField(blank=True, max_length=100, null=True, verbose_name='点检项目1')),
                ('check_item2', models.CharField(blank=True, max_length=100, null=True, verbose_name='点检项目2')),
                ('check_item3', models.CharField(blank=True, max_length=100, null=True, verbose_name='点检项目3')),
                ('check_item4', models.CharField(blank=True, max_length=100, null=True, verbose_name='点检项目4')),
                ('check_item5', models.CharField(blank=True, max_length=100, null=True, verbose_name='点检项目5')),
                ('check_item6', models.CharField(blank=True, max_length=100, null=True, verbose_name='点检项目6')),
                ('check_item7', models.CharField(blank=True, max_length=100, null=True, verbose_name='点检项目7')),
                ('check_item8', models.CharField(blank=True, max_length=100, null=True, verbose_name='点检项目8')),
                ('check_item9', models.CharField(blank=True, max_length=100, null=True, verbose_name='点检项目9')),
                ('check_item10', models.CharField(blank=True, max_length=100, null=True, verbose_name='点检项目10')),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
            ],
        ),
        migrations.CreateModel(
            name='Operater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='手机号')),
                ('banzu', models.IntegerField(blank=True, choices=[(1, '架车班'), (2, '轮轴班'), (3, '台车班'), (4, '内制动班'), (5, '外制动班'), (6, '车钩班'), (7, '探伤班'), (8, '调车组'), (9, '车体班'), (10, '预修班'), (11, '质检组'), (12, '信息班'), (13, '干部')], null=True, verbose_name='所属班组')),
                ('chejian', models.IntegerField(blank=True, choices=[(1, '检修车间'), (2, '设备车间')], null=True, verbose_name='所属车间')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(verbose_name='检查时间')),
                ('create_time1', models.DateTimeField(blank=True, null=True, verbose_name='完工检查时间')),
                ('check_item1', models.BooleanField(default=False)),
                ('check_item2', models.BooleanField(default=False)),
                ('check_item3', models.BooleanField(default=False)),
                ('check_item4', models.BooleanField(default=False)),
                ('check_item5', models.BooleanField(default=False)),
                ('check_item6', models.BooleanField(default=False)),
                ('check_item7', models.BooleanField(default=False)),
                ('check_item8', models.BooleanField(default=False)),
                ('check_item9', models.BooleanField(default=False)),
                ('check_item10', models.BooleanField(default=False)),
                ('beizhu', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('pic1', models.ImageField(blank=True, null=True, upload_to='inspection/', verbose_name='点检照片1')),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='inspection/', verbose_name='点检照片2')),
                ('pic3', models.ImageField(blank=True, null=True, upload_to='inspection/', verbose_name='点检照片3')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xfgl.equipment')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xfgl.operater')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_equipments', to='xfgl.operater', verbose_name='负责人'),
        ),
    ]
