# Generated by Django 5.0.4 on 2026-02-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xfgl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='banzu',
            field=models.IntegerField(blank=True, choices=[(1, '架车班'), (2, '轮轴班'), (3, '台车班'), (4, '内制动班'), (5, '外制动班'), (6, '车钩班'), (7, '探伤班'), (8, '调车组'), (9, '车体班'), (10, '预修班'), (12, '信息班')], null=True, verbose_name='所属班组'),
        ),
        migrations.AlterField(
            model_name='operater',
            name='banzu',
            field=models.IntegerField(blank=True, choices=[(1, '架车班'), (2, '轮轴班'), (3, '台车班'), (4, '内制动班'), (5, '外制动班'), (6, '车钩班'), (7, '探伤班'), (8, '调车组'), (9, '车体班'), (10, '预修班'), (12, '信息班'), (13, '干部')], null=True, verbose_name='所属班组'),
        ),
    ]
