# Generated by Django 5.0.4 on 2025-10-22 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banzu', models.IntegerField(choices=[(1, '架车班'), (2, '轮轴班'), (3, '台车班'), (4, '内制动班'), (5, '外制动班'), (6, '车钩班'), (7, '探伤班'), (8, '调车组'), (9, '车体班'), (10, '预修班'), (12, '信息班')], verbose_name='班组')),
                ('shijian', models.DateTimeField(verbose_name='学习时间')),
                ('didian', models.TextField(blank=True, null=True, verbose_name='学习地点')),
                ('zhuchiren', models.TextField(blank=True, null=True, verbose_name='主持人')),
                ('renyuan1', models.IntegerField(blank=True, null=True, verbose_name='应到人员')),
                ('renyuan2', models.IntegerField(blank=True, null=True, verbose_name='实到人员')),
                ('renyuan3', models.TextField(blank=True, null=True, verbose_name='请假人员及原因')),
                ('neirong', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='meeting/%Y/%m/%d/', verbose_name='学习现场照片')),
                ('pic1', models.ImageField(blank=True, null=True, upload_to='meeting/%Y/%m/%d/', verbose_name='签到照片')),
            ],
        ),
        migrations.CreateModel(
            name='TeamUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banzu', models.IntegerField(choices=[(1, '架车班'), (2, '轮轴班'), (3, '台车班'), (4, '内制动班'), (5, '外制动班'), (6, '车钩班'), (7, '探伤班'), (8, '调车组'), (9, '车体班'), (10, '预修班'), (12, '信息班'), (15, '修配综合班'), (16, '修车综合班')], verbose_name='班组')),
                ('jineng', models.IntegerField(blank=True, choices=[(1, '车辆钳工'), (2, '制动钳工（外）'), (3, '制动钳工（内）'), (4, '熔焊工'), (5, '探伤工'), (6, '轮轴装修工'), (7, '连接员'), (8, '轨道车司机'), (9, '铆工')], null=True, verbose_name='工种')),
                ('certificate', models.TextField(blank=True, null=True, verbose_name='持证情况')),
                ('dengji', models.IntegerField(blank=True, choices=[(1, '初级工'), (2, '中级工'), (3, '高级工'), (4, '技师'), (5, '高级技师')], null=True, verbose_name='技能等级')),
                ('marriage', models.IntegerField(blank=True, choices=[(1, '已婚'), (2, '未婚')], null=True, verbose_name='婚姻状况')),
                ('retire', models.IntegerField(choices=[(1, '在职'), (2, '退休'), (3, '调离')], default=1, verbose_name='在职/退休/调离')),
                ('gender', models.IntegerField(blank=True, choices=[(1, '男'), (2, '女')], null=True, verbose_name='性别')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='出生年月日')),
                ('name', models.TextField(verbose_name='姓名')),
                ('number', models.TextField(blank=True, null=True, verbose_name='电话号码')),
                ('wenhua', models.IntegerField(blank=True, choices=[(1, '初中'), (2, '高中'), (3, '中专'), (4, '中技'), (5, '大学专科'), (6, '大学本科'), (7, '研究生及以上')], null=True, verbose_name='文化程度')),
                ('jiguan', models.TextField(blank=True, null=True, verbose_name='籍贯')),
                ('mianmao', models.IntegerField(blank=True, choices=[(1, '团员'), (2, '群众'), (3, '党员')], null=True, verbose_name='政治面貌')),
                ('didian', models.TextField(blank=True, null=True, verbose_name='探亲地点')),
                ('leibie', models.IntegerField(blank=True, choices=[(1, '探父母'), (2, '探配偶')], null=True, verbose_name='探亲类别')),
                ('award', models.TextField(blank=True, null=True, verbose_name='获奖情况')),
                ('beizhu', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('熔化焊接与热切割作业', '熔化焊接与热切割作业'), ('A.特种设备安全管理', 'A.特种设备安全管理'), ('Q1.起重机指挥', 'Q1.起重机指挥'), ('Q2.起重机司机', 'Q2.起重机司机'), ('N1.叉车司机', 'N1.叉车司机')], max_length=100)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='bzrz.teamuser')),
            ],
        ),
    ]
