# Generated by Django 5.0.4 on 2026-02-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bzrz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamuser',
            name='banzu',
            field=models.IntegerField(choices=[(1, '架车班'), (2, '轮轴班'), (3, '台车班'), (4, '内制动班'), (5, '外制动班'), (6, '车钩班'), (7, '探伤班'), (8, '调车组'), (9, '车体班'), (10, '预修班'), (12, '信息班'), (15, '修配综合班'), (16, '修车综合班'), (17, '修配领导'), (18, '修车领导')], verbose_name='班组'),
        ),
    ]
