# Generated by Django 5.0.4 on 2025-02-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='时间')),
                ('meeting', models.TextField(verbose_name='会议主题')),
                ('Contents1', models.TextField(blank=True, null=True, verbose_name='会议内容1')),
                ('Contents2', models.TextField(blank=True, null=True, verbose_name='会议内容2')),
                ('Contents3', models.TextField(blank=True, null=True, verbose_name='会议内容3')),
                ('Contents4', models.TextField(blank=True, null=True, verbose_name='会议内容4')),
                ('Contents5', models.TextField(blank=True, null=True, verbose_name='会议内容5')),
            ],
        ),
    ]
