# Generated by Django 5.0.4 on 2025-02-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='Contents',
            field=models.TextField(blank=True, null=True, verbose_name='议定事项'),
        ),
    ]
