# Generated by Django 5.0.4 on 2025-02-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_meeting_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='Contents6',
            field=models.TextField(blank=True, null=True, verbose_name='会议内容6'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='Contents7',
            field=models.TextField(blank=True, null=True, verbose_name='会议内容7'),
        ),
    ]
