# Generated by Django 5.0.4 on 2025-02-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_meeting_contents6_meeting_contents7'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='时间'),
        ),
    ]
