# Generated by Django 5.0.4 on 2025-05-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_alter_meeting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting1',
            field=models.TextField(default=1, verbose_name='副标题'),
            preserve_default=False,
        ),
    ]
