# Generated by Django 5.0.4 on 2025-05-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_meeting_meeting1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting1',
            field=models.TextField(blank=True, null=True, verbose_name='副标题'),
        ),
    ]
