# Generated by Django 5.0.4 on 2026-03-08 22:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app01', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='maintenance_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='工具编码')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('specification', models.CharField(max_length=200, verbose_name='规格')),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True, verbose_name='厂家名称')),
                ('purchase_date', models.DateField(verbose_name='购买日期')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价值(元)')),
                ('is_high_value', models.BooleanField(choices=[(False, '普通工具'), (True, '高价值工具')], default=False, help_text='价值≥1000元的工具建议选择高价值工具', verbose_name='工具类型')),
                ('status', models.CharField(choices=[('正常', '正常'), ('故障', '故障'), ('维修', '维修'), ('报废', '报废')], default='正常', max_length=20, verbose_name='状态')),
                ('maintenance_cycle', models.IntegerField(choices=[(1, '每天'), (7, '一周'), (30, '一个月'), (60, '两个月'), (90, '三个月'), (180, '半年'), (365, '一年')], default=30, help_text='工具保养的时间间隔', verbose_name='保养周期(天)')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='上次保养日期')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tool_images/', verbose_name='图片')),
                ('technical_docs', models.FileField(blank=True, null=True, upload_to='tech_docs/', verbose_name='技术文档')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '工具',
                'verbose_name_plural': '工具',
            },
        ),
        migrations.CreateModel(
            name='ToolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '工具分类',
                'verbose_name_plural': '工具分类',
            },
        ),
        migrations.CreateModel(
            name='SimpleTeamPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop', models.IntegerField(choices=[(0, '管理员'), (1, '修配车间'), (2, '修车车间')], verbose_name='车间')),
                ('team', models.IntegerField(choices=[(1, '架车班'), (2, '轮轴班'), (3, '台车班'), (4, '内制动班'), (5, '外制动班'), (6, '车钩班'), (7, '探伤班'), (8, '调车组'), (9, '车体班'), (10, '预修班'), (12, '信息班'), (13, '干部')], verbose_name='班组')),
                ('can_manage_tools', models.BooleanField(default=False, verbose_name='工具管理权限')),
                ('can_manage_categories', models.BooleanField(default=False, verbose_name='分类管理权限')),
                ('can_approve_loans', models.BooleanField(default=False, verbose_name='申领审批权限')),
                ('can_approve_returns', models.BooleanField(default=False, verbose_name='归还审批权限')),
                ('can_perform_maintenance', models.BooleanField(default=False, verbose_name='执行保养权限')),
                ('can_manage_repairs', models.BooleanField(default=False, verbose_name='维修管理权限')),
                ('can_view_records', models.BooleanField(default=False, verbose_name='查看记录权限')),
                ('team_leader_username', models.CharField(blank=True, max_length=32, verbose_name='班组长用户名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '班组权限配置',
                'verbose_name_plural': '班组权限配置',
                'unique_together': {('workshop', 'team')},
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.admin')),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='班组名称')),
                ('can_borrow_tools', models.BooleanField(default=True, verbose_name='可申领工具')),
                ('can_manage_custody', models.BooleanField(default=False, verbose_name='可管理保管')),
                ('can_perform_maintenance', models.BooleanField(default=False, verbose_name='可执行保养')),
                ('can_approve_loans', models.BooleanField(default=False, verbose_name='可审批申领')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_teams', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '班组',
                'verbose_name_plural': '班组',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('班组长', '班组长'), ('操作员', '操作员'), ('信息管理员', '信息管理员'), ('车间主任', '车间主任')], default='操作员', max_length=20, verbose_name='职务')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.team', verbose_name='所属班组')),
            ],
            options={
                'verbose_name': '用户档案',
                'verbose_name_plural': '用户档案',
            },
        ),
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('日检', '日检'), ('周检', '周检'), ('月检', '月检')], max_length=20, verbose_name='检查类型')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='检查日期')),
                ('result', models.TextField(verbose_name='检查结果')),
                ('issues_found', models.TextField(blank=True, verbose_name='发现问题')),
                ('rectification_required', models.TextField(blank=True, verbose_name='整改要求')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='考核评分')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.admin', verbose_name='检查人')),
                ('inspected_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.team', verbose_name='被检班组')),
            ],
            options={
                'verbose_name': '检查记录',
                'verbose_name_plural': '检查记录',
            },
        ),
        migrations.CreateModel(
            name='TeamPermissionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop', models.IntegerField(choices=[(0, '管理员'), (1, '修配车间'), (2, '修车车间')], verbose_name='车间')),
                ('team', models.IntegerField(choices=[(1, '架车班'), (2, '轮轴班'), (3, '台车班'), (4, '内制动班'), (5, '外制动班'), (6, '车钩班'), (7, '探伤班'), (8, '调车组'), (9, '车体班'), (10, '预修班'), (12, '信息班'), (13, '干部')], verbose_name='班组')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='管理用户')),
                ('can_manage_tools', models.BooleanField(default=False, verbose_name='管理工具')),
                ('can_approve_loans', models.BooleanField(default=False, verbose_name='审批申领')),
                ('can_perform_maintenance', models.BooleanField(default=False, verbose_name='执行保养')),
                ('can_manage_repairs', models.BooleanField(default=False, verbose_name='管理维修')),
                ('team_leader_username', models.CharField(blank=True, max_length=32, verbose_name='班组长用户名')),
            ],
            options={
                'verbose_name': '班组权限配置',
                'verbose_name_plural': '班组权限配置',
                'unique_together': {('workshop', 'team')},
            },
        ),
        migrations.CreateModel(
            name='RepairRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_description', models.TextField(verbose_name='故障描述')),
                ('report_time', models.DateTimeField(auto_now_add=True, verbose_name='报修时间')),
                ('repair_status', models.CharField(choices=[('待维修', '待维修'), ('已完成', '已完成')], default='待维修', max_length=20, verbose_name='维修状态')),
                ('repair_unit', models.CharField(blank=True, max_length=100, verbose_name='维修单位')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='费用 (元)')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='维修说明')),
                ('liability_identified', models.BooleanField(default=False, verbose_name='是否已认定责任')),
                ('liability_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='赔偿金额 (元)')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.admin', verbose_name='报修人')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.tool', verbose_name='工具')),
            ],
            options={
                'verbose_name': '维修记录',
                'verbose_name_plural': '维修记录',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('日常', '日常'), ('定期', '定期'), ('校准', '校准')], max_length=20, verbose_name='保养类型')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日期')),
                ('content', models.TextField(verbose_name='保养内容')),
                ('result', models.TextField(verbose_name='保养结果')),
                ('images', models.ManyToManyField(blank=True, to='tools.maintenanceimage', verbose_name='相关图片')),
                ('maintainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.admin', verbose_name='保养人')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.tool', verbose_name='工具')),
            ],
            options={
                'verbose_name': '保养记录',
                'verbose_name_plural': '保养记录',
            },
        ),
        migrations.AddField(
            model_name='tool',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.toolcategory', verbose_name='类别'),
        ),
        migrations.CreateModel(
            name='ToolLoanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowing_team', models.CharField(help_text='申领工具的班组名称', max_length=50, verbose_name='申领班组')),
                ('borrowing_person', models.CharField(help_text='实际使用工具的人员姓名', max_length=50, verbose_name='申领人')),
                ('borrowing_person_id', models.IntegerField(blank=True, help_text='申领人对应的TeamUser ID，用于关联查询', null=True, verbose_name='申领人ID')),
                ('loan_time', models.DateTimeField(auto_now_add=True, verbose_name='申领时间')),
                ('expected_return_time', models.DateTimeField(blank=True, null=True, verbose_name='预计归还时间')),
                ('actual_return_time', models.DateTimeField(blank=True, null=True, verbose_name='实际归还时间')),
                ('status', models.CharField(choices=[('已申请', '已申请'), ('已发放', '已发放'), ('归还申请', '归还申请'), ('已归还', '已归还'), ('逾期', '逾期')], default='已申请', max_length=20)),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.admin', verbose_name='申领人')),
                ('return_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_approved_loans', to='app01.admin', verbose_name='归还审批人')),
                ('team_leader_approval', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to='app01.admin', verbose_name='班组长审批')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.tool', verbose_name='工具')),
            ],
            options={
                'verbose_name': '工具申领记录',
                'verbose_name_plural': '工具申领记录',
            },
        ),
        migrations.CreateModel(
            name='ToolsUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access_tools', models.BooleanField(default=False, verbose_name='可访问工具管理系统')),
                ('tools_role', models.CharField(choices=[('system_admin', '系统管理员'), ('workshop_director', '车间主任'), ('info_admin', '信息管理员'), ('tools_manager', '工具管理员'), ('dispatcher', '调度员'), ('safety_officer', '安全员'), ('technician', '技术员'), ('foreman', '班组长'), ('operator', '操作员')], default='operator', max_length=20, verbose_name='工具系统角色')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='可管理用户')),
                ('can_manage_teams', models.BooleanField(default=False, verbose_name='可管理班组')),
                ('can_manage_tools', models.BooleanField(default=False, verbose_name='可管理工具')),
                ('can_manage_categories', models.BooleanField(default=False, verbose_name='可管理工具分类')),
                ('can_approve_loans', models.BooleanField(default=False, verbose_name='可审批申领')),
                ('can_perform_maintenance', models.BooleanField(default=False, verbose_name='可执行保养')),
                ('can_manage_repairs', models.BooleanField(default=False, verbose_name='可管理维修')),
                ('can_view_reports', models.BooleanField(default=False, verbose_name='可查看报表')),
                ('can_manage_permissions', models.BooleanField(default=False, verbose_name='可管理权限')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.admin', verbose_name='系统用户')),
                ('assigned_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.team', verbose_name='分配班组')),
            ],
            options={
                'verbose_name': '工具系统用户配置',
                'verbose_name_plural': '工具系统用户配置',
            },
        ),
        migrations.CreateModel(
            name='UserPermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_can_manage_users', models.BooleanField(blank=True, null=True, verbose_name='管理用户权限')),
                ('override_can_manage_tools', models.BooleanField(blank=True, null=True, verbose_name='管理工具权限')),
                ('override_can_approve_loans', models.BooleanField(blank=True, null=True, verbose_name='审批申领权限')),
                ('override_can_perform_maintenance', models.BooleanField(blank=True, null=True, verbose_name='执行保养权限')),
                ('override_can_manage_repairs', models.BooleanField(blank=True, null=True, verbose_name='管理维修权限')),
                ('effective_from', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('admin_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.admin', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='TeamPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_borrow', models.BooleanField(default=False, verbose_name='可申领')),
                ('can_manage', models.BooleanField(default=False, verbose_name='可管理')),
                ('can_maintain', models.BooleanField(default=False, verbose_name='可保养')),
                ('borrow_limit', models.IntegerField(default=0, verbose_name='申领数量限制')),
                ('approval_required', models.BooleanField(default=True, verbose_name='需要审批')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.team', verbose_name='班组')),
                ('tool_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.toolcategory', verbose_name='工具类别')),
            ],
            options={
                'verbose_name': '班组权限配置',
                'verbose_name_plural': '班组权限配置',
                'unique_together': {('team', 'tool_category')},
            },
        ),
    ]
