# Generated by Django 5.0.4 on 2026-04-28 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolloanrecord',
            name='loan_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='申领时间'),
        ),
    ]
