# Generated by Django 5.0.4 on 2026-03-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionrecord',
            name='inspected_team',
        ),
        migrations.RemoveField(
            model_name='inspectionrecord',
            name='inspector',
        ),
        migrations.RemoveField(
            model_name='systemlog',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='teampermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='teampermission',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teampermission',
            name='tool_category',
        ),
        migrations.DeleteModel(
            name='TeamPermissionConfig',
        ),
        migrations.RemoveField(
            model_name='userpermissionoverride',
            name='admin_user',
        ),
        migrations.DeleteModel(
            name='InspectionRecord',
        ),
        migrations.DeleteModel(
            name='SystemLog',
        ),
        migrations.DeleteModel(
            name='TeamPermission',
        ),
        migrations.DeleteModel(
            name='UserPermissionOverride',
        ),
    ]
