# Generated by Django 5.0.4 on 2026-03-16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_remove_unused_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToolsUserProfile',
        ),
    ]